### ISSUE TITLE
Return user groups so flow builders can make decisions in the flow

### ISSUE THREAD

**Issue by matt-manywho** [manywho/service-saml#17]
Currently $User / Primary Group Name or $User / Primary Group Id aren't populated, so only swimlanes can be used to make decisions in a flow about a users group information

**Comment by josecollazzi** [comment]
@matt-manywho In case you want to take a look I have made a new PR for this issue https://github.com/manywho/service-saml/pull/20

**Comment by josecollazzi** [comment]
This functionality have been merged in master in the pull request:

https://github.com/manywho/service-saml/pull/37
